name: ScriptedEvents Build
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:
env:
  REFERENCES_URL: https://exiled.host/build_deps/Dev.zip
  REFERENCES_PATH: ${{ github.workspace }}/References
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup NuGet
        uses: iRebbok/setup-nuget@master

      - uses: actions/checkout@v2

      - name: Restore NuGet
        run: nuget restore ScriptedEvents.sln

      - name: Get Build References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile ${{ github.workspace }}/Dev.zip
          Expand-Archive -Path Dev.zip -DestinationPath ${{ env.REFERENCES_PATH }}
      - name: Build
        run: |
          ./build.ps1 -BuildNuGet
          $File = (Get-ChildItem -Path . -Include 'EXILED.*.nupkg' -Recurse).Name
          Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Results
          path: bin/Release
