name: ScriptedEvents Build
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - uses: actions/checkout@v2

      - name: Restore Packages
        run: nuget restore

      - name: Setup MSBuild.exe
        uses: microsoft/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build
        run: | 
          msbuild ScriptedEvents\ScriptedEvents.csproj /t:restore /p:configuration="Release" /p:ReferencePath="${{ env.REFERENCES_PATH }}" 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Scripted Events
          path: "ScriptedEvents/bin/Release/ScriptedEvents.dll"